server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

info:
  app:
    name: ${spring.application.name}
    description: Eureka Discovery Server for service registration and discovery.
    version: 0.0.1-SNAPSHOT
    environment: local
  author: CodesBG
