spring:
  application:
    name: gateway-service
  config:
    activate:
      on-profile: client

server:
  port: 8080

info:
  app:
    name: ${spring.application.name}
    description: API Gateway for routing and filtering requests between microservices.
    version: 0.0.1-SNAPSHOT
    environment: local
  author: CodesBG